// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using falastroes_no_comando.Context;

#nullable disable

namespace falastroes_no_comando.Migrations
{
    [DbContext(typeof(FalastroesContext))]
    [Migration("20250726195524_StartingDbFalastroes")]
    partial class StartingDbFalastroes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("falastroes_no_comando.Models.Political", b =>
                {
                    b.Property<int>("IdPolitical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPolitical"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<string>("Status_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPolitical");

                    b.ToTable("Political", (string)null);
                });

            modelBuilder.Entity("falastroes_no_comando.Models.Political_has_Proposal", b =>
                {
                    b.Property<int>("IdPolitical_has_Proposal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPolitical_has_Proposal"));

                    b.Property<int>("IdPolitical")
                        .HasColumnType("int");

                    b.Property<int>("IdProposal")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalIdPolitical")
                        .HasColumnType("int");

                    b.Property<int>("ProposalIdProposal")
                        .HasColumnType("int");

                    b.HasKey("IdPolitical_has_Proposal");

                    b.HasIndex("PoliticalIdPolitical");

                    b.HasIndex("ProposalIdProposal");

                    b.ToTable("Political_has_Proposal", (string)null);
                });

            modelBuilder.Entity("falastroes_no_comando.Models.Proposal", b =>
                {
                    b.Property<int>("IdProposal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProposal"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProposal");

                    b.ToTable("Proposal", (string)null);
                });

            modelBuilder.Entity("falastroes_no_comando.Models.Political_has_Proposal", b =>
                {
                    b.HasOne("falastroes_no_comando.Models.Political", "Political")
                        .WithMany("political_Has_Proposals")
                        .HasForeignKey("PoliticalIdPolitical")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("falastroes_no_comando.Models.Proposal", "Proposal")
                        .WithMany("Political_Has_Proposals")
                        .HasForeignKey("ProposalIdProposal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Political");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("falastroes_no_comando.Models.Political", b =>
                {
                    b.Navigation("political_Has_Proposals");
                });

            modelBuilder.Entity("falastroes_no_comando.Models.Proposal", b =>
                {
                    b.Navigation("Political_Has_Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
